<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-0PBS36T" name="LoginTests" tests="4" failures="1" timestamp="30 Dec 2020 05:37:34 GMT" time="242.963" errors="0">
  <testcase name="successfulLogin" time="83.115" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <testcase name="successfulLogin" time="66.126" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <testcase name="successfulLogin" time="38.092" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- successfulLogin -->
  <testcase name="successfulLogin" time="55.394" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]">
      <![CDATA[java.lang.AssertionError: expected [https://opensource-demo.orangehrmlive.com/index.php/dashboard] but found [https://opensource-demo.orangehrmlive.com/index.php/auth/validateCredentials]
	at tests.LoginTests.successfulLogin(LoginTests.java:53)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- successfulLogin -->
</testsuite> <!-- LoginTests -->
